- .travis.yml
> ci: multi os supports

- src/storage/mod.rs
Refs: 
* [std::error::Error::downcast_ref](https://doc.rust-lang.org/nightly/std/error/trait.Error.html#method.downcast_ref)
* [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6071da1f86b80570004c1493b6551c82)
> Use downcast_ref instead of unsafe cast

- src/db/filename.rs
I add some code to test_generate_filename supports windows, `cargo test` output is Ok
> src/db/filename.rs test_generate_filename functions supports windows

- src/cache/lru.rs
- src/cache/mod.rs
- src/compaction.rs
- src/db/mod.rs
- src/sstable/table.rs
- src/storage/mem.rs
- src/table_cache.rs
- src/version/mod.rs
- src/version/version_set.rs
https://github.com/Fullstop000/wickdb/issues/4
> refactor: rename getter for RFC #344

- benches/mem/arena.rs
- benches/mem/skiplist.rs
- src/mem/mod.rs
- src/mem/skiplist.rs
Part of https://github.com/Fullstop000/wickdb/issues/17
> Refactor skiplist by using Generic

- .travis.yml
> Adjust travis ci

- .travis.yml
Close https://github.com/Fullstop000/wickdb/issues/27
> ci: Try to reduce the CI time

- examples/simple_read_write.rs
- src/compaction.rs
- src/db/filename.rs
- src/db/iterator.rs
- src/db/mod.rs
- src/lib.rs
- src/options.rs
- src/sstable/mod.rs
- src/storage/file.rs
- src/storage/mod.rs
- src/table_cache.rs
- src/version/mod.rs
- src/version/version_set.rs
> *: use generic Storage

- examples/simple_read_write.rs
- src/batch.rs
- src/compaction.rs
- src/db/format.rs
- src/db/iterator.rs
- src/db/mod.rs
- src/filter/bloom.rs
- src/filter/mod.rs
- src/iterator.rs
- src/mem/mod.rs
- src/mem/skiplist.rs
- src/record/mod.rs
- src/record/writer.rs
- src/sstable/block.rs
- src/sstable/filter_block.rs
- src/sstable/mod.rs
- src/sstable/table.rs
- src/table_cache.rs
- src/util/comparator.rs
- src/version/mod.rs
- src/version/version_edit.rs
- src/version/version_set.rs
Relate to https://github.com/Fullstop000/wickdb/issues/24
> Remove a lot of Slice usage

- src/compaction.rs
- src/db/filename.rs
- src/db/mod.rs
- src/logger.rs
- src/options.rs
- src/record/mod.rs
- src/record/reader.rs
- src/record/writer.rs
- src/sstable/mod.rs
- src/sstable/table.rs
- src/storage/file.rs
- src/storage/mem.rs
- src/storage/mod.rs
- src/table_cache.rs
- src/util/comparator.rs
- src/version/version_set.rs
> use associate type File in Storage

- src/cache/lru.rs
- src/cache/mod.rs
- src/compaction.rs
- src/db/mod.rs
- src/iterator.rs
- src/lib.rs
- src/options.rs
- src/sstable/mod.rs
- src/sstable/table.rs
- src/table_cache.rs
- src/version/version_set.rs
- Use a safer implementation for `LRUCache`
- Remove `IterWithCleanup`
> Use a safer LRU implmentation

- src/sstable/block.rs
- src/sstable/table.rs
- src/table_cache.rs
- src/version/mod.rs
Temporarily solved https://github.com/Fullstop000/wickdb/issues/46.
Such UB problem will be solved until `Slice` is totally removed.
> block: fix potential UB caused by BlockIterator

- src/compaction.rs
- src/db/mod.rs
- src/iterator.rs
- src/version/version_set.rs
Remove `CompactionInputsRelation` and make cargo clippy happy
> compaction: remove CompactionInputsRelation

- src/version/version_set.rs
Use current newest `Version` as the base version in `VersionBuilder`
> fix log_and_apply

- src/compaction.rs
- src/db/format.rs
- src/db/mod.rs
- src/logger.rs
- src/mem/arena.rs
- src/mem/mod.rs
- src/mem/skiplist.rs
- src/snapshot.rs
- src/sstable/table.rs
- src/version/mod.rs
- src/version/version_edit.rs
- src/version/version_set.rs
Part of https://github.com/Fullstop000/wickdb/issues/3
> Add basic test cases for WickDB/DBImpl

- src/db/format.rs
- src/db/mod.rs
- src/mem/mod.rs
- src/sstable/mod.rs
- src/util/varint.rs
Part of https://github.com/Fullstop000/wickdb/issues/3
> Add tests for DBIterator

- src/db/mod.rs
- src/options.rs
- src/storage/file.rs
- src/version/mod.rs
- src/version/version_set.rs
Add a test case for db recovery in memory table compaction
Relate to https://github.com/Fullstop000/wickdb/issues/3
> test: memory table compaction recovery

- .travis.yml
> ci: use grcov

- src/batch.rs
- src/cache/lru.rs
- src/compaction.rs
- src/db/iterator.rs
- src/db/mod.rs
- src/iterator.rs
- src/mem/mod.rs
- src/mem/skiplist.rs
- src/sstable/block.rs
- src/sstable/mod.rs
- src/sstable/table.rs
- src/util/collection.rs
- src/util/slice.rs
- src/version/mod.rs
- src/version/version_set.rs
Fix https://github.com/Fullstop000/wickdb/issues/49
Relate to https://github.com/Fullstop000/wickdb/issues/24
Also close https://github.com/Fullstop000/wickdb/pull/58
> *: Remove slice in Iterator

- .travis.yml
> ci: clean up targets before grcov

- rust-toolchain
- src/db/mod.rs
- src/mem/mod.rs
- src/mem/skiplist.rs
- src/util/slice.rs
- src/version/mod.rs
Relate to https://github.com/Fullstop000/wickdb/issues/24
> *: remove more Slice

- src/cache/lru.rs
- src/cache/mod.rs
- src/options.rs
> cache: introduce sharded LRU

- .travis.yml
- rust-toolchain
- src/compaction.rs
- src/db/mod.rs
- src/iterator.rs
- src/options.rs
- src/sstable/block.rs
- src/sstable/mod.rs
- src/sstable/table.rs
- src/version/mod.rs
- src/version/version_set.rs
- add test_compaction_generate_multiple_files
- fix some tests
> Add test_compaction_generate_multiple_files

- src/db/mod.rs
- src/sstable/table.rs
- src/version/mod.rs
- src/version/version_set.rs
> add test_approximate_size

- src/db/format.rs
- src/db/mod.rs
- src/snapshot.rs
- src/version/version_set.rs
> add more tests

- src/cache/lru.rs
- src/cache/mod.rs
- src/db/mod.rs
- src/options.rs
- src/sstable/mod.rs
- src/sstable/table.rs
- src/table_cache.rs
> cache: make LRU become safer

- .github/workflows/test.yml
- README.md
- rust-toolchain
- src/db/format.rs
- src/db/mod.rs
- src/lib.rs
- src/mem/mod.rs
> *: fix clippy and update doc

- src/cache/lru.rs
- src/cache/mod.rs
- src/db/format.rs
- src/db/mod.rs
- src/filter/mod.rs
- src/mem/arena.rs
- src/mem/inlineskiplist.rs
- src/options.rs
- src/sstable/block.rs
- src/sstable/filter_block.rs
- src/sstable/table.rs
> test: add multi-thread tests

- src/db/filename.rs
- src/db/mod.rs
- src/options.rs
- src/storage/mod.rs
- src/table_cache.rs
- src/version/version_set.rs
> *: replace 'db_name' with 'db_path'

- src/lib.rs
> clippy: allow rc-buffer

- examples/simple_read_write.rs
- src/db/mod.rs
- src/options.rs
> polish example simple_read_write
